### ISSUE TITLE
VLA archive file 22B-193.sb43004841.eb45211507.60337.64330296296

### ISSUE THREAD

**Issue by xinglunju** [ACES-CMZ/reduction_JACKS#14]
SB 43004841
JACKS region 17

- [x] Observations completed
- [x] VLA CASA Calibration pipeline run by observatory
- [x] [Weblog](https://mills.ku.edu/JACKS/2024_01_30_T21_32_17/pipeline-20240130T230623/html) downloaded and unpacked
- [x] Raw data downloaded (specify where)
  - [x] local machine
  - [ ] Globus
- [ ] Pipeline calibration assessment 
- [ ] Calibrated MS generated
   - [ ] Uploaded to Globus
- [ ] Imaging: Continuum
- [ ] Imaging: Lines
   - [ ] NH3 (1,1)
   - [ ] NH3 (2,2)
   - [ ] NH3 (3,3)
   - [ ] NH3 (4,4)
   - [ ] NH3 (5,5)
   - [ ] H2O
   - [ ] H64
   - [ ] H66
   - [ ] NH3 (2,1)
   - [ ] NH3 (3,2)
   - [ ] NH3 (4,3)
   - [ ] NH3 (5,4)
   - [ ] NH3 (6,5)
 ## Product Links

**Comment by xinglunju** [comment]
Log Name:                  2024-01-28_1526_22B-193
Project:                   22B-193
SBID(s):                   43004841
EBID(s):                   45211507
Observing Date:            28-Jan-2024
Observation Type:          Science
Bands Used:                X K
No. Subarrays:               1
Observer(PI):              Prof Elisabeth Mills
Source File(s):            22B-193_sb43004841_1_1
Operator(s):               Jesse Petrone
Array Configuration:       C
Decommissioned Antenna:     28

Adobe PDF version of this log is located at:
http://www.vla.nrao.edu/operators/logs/


***** WEATHER INFORMATION *****

Time(UTC)        Dew Pt  Temp   Wind           Bar Press    API RMS Phase(degs)
28Jan 15:27:57   -6.6    -6.1   NW at 0.6 m/s  796.3        1.8
28Jan 16:01:40   -4.8    -3.7   NW at 1.0 m/s  796.3        2.9
28Jan 18:18:29   -3.8    5.4    W at 0.7 m/s   796.4        6.3
28Jan 19:00:57   -5.2    8.5    W at 0.7 m/s   795.5        5.9

*** Operator comments for the above weather entries ***

28Jan 15:27:57     Sky clear.                           
28Jan 16:01:40     Sky clear.                           
28Jan 18:18:29     Sky cover 10%.   Stratiform clouds. 
28Jan 19:00:57     Sky cover 30%.   Stratiform clouds. 


***** COMMENTS AND OUTAGES *****

Outage information format:
Start Time, End Time, Category, Form#, # Antennas, Down Time(minutes)
Antenna ID(s) and Data Effect
Description


Number of Antennas Used: 27

28Jan 15:26:18 
Starting project 22B-193.

28Jan 15:26:18 
The band(s) used is(are): X K.

30Dec 15:26:18 
On source 3C286 with all available antennas.

28Jan 15:26:18 
Antenna(s):1,6,7,8,10,11,13,15,17,18,19,21,24,25,26,27
have recently updated baseline parameters to correct for errors resulting from
their recent relocation.  Please check for any significant errors and submit
them to the NRAO Helpdesk (https://science.nrao.edu/observing/helpdesk)
under the VLA Observing department.

28Jan 15:26:18 
To access your data from the NRAO archive visit:
https://science.nrao.edu/facilities/vla/archive
All VLA science data are processed through the VLA calibration pipeline. Details
are at: https://science.nrao.edu/facilities/vla/data-processing/pipeline
For further questions please use the NRAO Helpdesk at:
https://science.nrao.edu/observing/helpdesk
Adobe PDF version of this log is located at:
http://www.vla.nrao.edu/operators/logs/

28Jan 15:26:18 
Note: To support our ongoing RFI monitoring efforts, any feedback from your
program on RFI can be sent to: [nrao-rfi@nrao.edu](mailto:nrao-rfi@nrao.edu)
The key information to provide is:
 - Observation/project code
 - Frequency and Time of the observations
 - The characteristics of the RFI signal, in particular if it is continuous or
   intermittent?
 - If possible, a spectrum of the RFI should be included in the e-mail.
Thanks very much for your support; this information will be continuously
updated on the EVLA science pages at:
https://science.nrao.edu/facilities/vla/docs/manuals/obsguide/modes/rfi/

28Jan 15:26:18   28Jan 18:55:45   SERVO             WO-18966      1.00   209.5
Antenna(s) 19 (Data: Lost):
Antenna parked due to elevation faults

28Jan 15:26:18   28Jan 18:55:45   CRYOGENICS        WO-20064      0.12   25.3
Antenna(s) 10 (Data: Corrupted):
K-band receiver warm, sensitivity degraded

28Jan 15:26:18   28Jan 18:55:45   FOCUS/ROTATION    Other         0.15   31.4
Antenna(s) 27 (Data: Lost):
Frequent subreflector faults or position errors.


Project End Time         Total Time            % Down Time   Total Down Time
                         (minutes x 27 ants)                 (minutes)

28-Jan-2024 18:55:45     5655.2                4.7%          266.2

**Comment by xinglunju** [comment]
#### Issues noted but not flagged by staff in pipeline run:
- There is gain compression evident in the observation.
- Antennas ea09 and ea12 have hardware issues.
- The low amplitude points in the calibrator UVwave plots are from ea15, spw 10.
- Baseline ea26&ea27 spw 9 is causing additional low amplitude points in the complex gain calibrator's UVwave plot.

**Comment by kelizabeth7** [comment]
**Task Step 13:**

Most of the phase gain cal plots have negative slopes
phase gain cal plots that are missing data points align with the antennae that were flagged >50% in phase calibrator (ea02, ea07, and ea27):

![Image](https://github.com/user-attachments/assets/0e1460b8-7fa9-4e3d-b96c-d7e160b0582c)
![Image](https://github.com/user-attachments/assets/13eb9182-4481-4190-8794-3f1bb6654617)
![Image](https://github.com/user-attachments/assets/b2194b43-ed3c-496e-aa00-7a1ee0d61cef)

final amp time cal plots that concerned me (ea09 and ea12):
the data points separate from each other - this is not the case in the other plots

![Image](https://github.com/user-attachments/assets/2dad8851-1c22-44af-9283-b756784ab6d9)
![Image](https://github.com/user-attachments/assets/bb897b91-3d39-46be-8c6a-6afbed02ccfa)

final amp freq cal plot that concerned me (ea09):
there's a larger vertical spread in the data than in the other plots - connection to the spread in the amp time cal plots?

![Image](https://github.com/user-attachments/assets/7dbaf7dd-ce33-4886-8fc6-7997ed9a105f)

**Task Step 17:**

summary phase vs time plots that concerned me (ea08):
the data extends up the left side of the plot further than any of the other target plots. the other plots have maximum amplitudes of approximately 0.10 whereas ea08 has a maximum of 0.30

![Image](https://github.com/user-attachments/assets/f10fa352-b375-4086-bda4-ba9c9996d787)


**Other Notes**
- no antenna 100% flagged in bandpass
- antenna flagged >50% in phase calibrator: ea02, ea07, ea10, ea27
- antenna flagged in source: ea02, ea07, ea27 (not 100%)
- all QA scores by task are 100% except for hfiv_fluxboot: Gain table for flux density bootstrapping at 91%
- beam size of phase calibrator image: 1.84 x 0.698 arc-seconds

**Comment by kelizabeth7** [comment]
Raw data has been downloaded to local machine.
